# Generated by Django 3.2 on 2021-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondate',
            name='production_date',
            field=models.CharField(max_length=128),
        ),
    ]
