# Generated by Django 3.2 on 2021-04-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='good',
        ),
    ]
